package com.vw.rent.mapper;

import com.vw.rent.entity.DictionaryType;
import java.util.List;

public interface DictionaryTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vw_dictionary_type
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vw_dictionary_type
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    int insert(DictionaryType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vw_dictionary_type
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    DictionaryType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vw_dictionary_type
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    List<DictionaryType> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vw_dictionary_type
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    int updateByPrimaryKey(DictionaryType record);
}