package com.vw.rent.mapper;

import com.vw.rent.entity.Dictionary;
import com.vw.rent.vo.DictionaryVo;

import java.util.List;

public interface DictionaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vw_dictionary
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vw_dictionary
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    int insert(Dictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vw_dictionary
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    Dictionary selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vw_dictionary
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    List<Dictionary> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vw_dictionary
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    int updateByPrimaryKey(Dictionary record);

    List<Dictionary> selectByTypeId(Integer type);

    List<DictionaryVo> getNewStatus();

    List<DictionaryVo> getFawStatus();
}