package com.vw.rent.mapper;

import com.vw.rent.entity.OrderStatusChange;
import java.util.List;

public interface OrderStatusChangeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vw_order_status_change
     *
     * @mbg.generated Fri Dec 27 10:37:17 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vw_order_status_change
     *
     * @mbg.generated Fri Dec 27 10:37:17 CST 2019
     */
    int insert(OrderStatusChange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vw_order_status_change
     *
     * @mbg.generated Fri Dec 27 10:37:17 CST 2019
     */
    OrderStatusChange selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vw_order_status_change
     *
     * @mbg.generated Fri Dec 27 10:37:17 CST 2019
     */
    List<OrderStatusChange> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vw_order_status_change
     *
     * @mbg.generated Fri Dec 27 10:37:17 CST 2019
     */
    int updateByPrimaryKey(OrderStatusChange record);

    List<OrderStatusChange> getRentStatus(Long orderNo);
}