
package com.vw.rent.ws.ecpFinProductCalibrationWrapper;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EcpFinProductCalibrationWrapperService", targetNamespace = "http://irwx503.ecpvw.credit.faf.com/", wsdlLocation = "http://af.test.17ebank.com:9167/csmWeb/ws/EcpFinProductCalibrationWrapper?wsdl")
public class EcpFinProductCalibrationWrapperService
    extends Service
{

    private final static URL ECPFINPRODUCTCALIBRATIONWRAPPERSERVICE_WSDL_LOCATION;
    private final static WebServiceException ECPFINPRODUCTCALIBRATIONWRAPPERSERVICE_EXCEPTION;
    private final static QName ECPFINPRODUCTCALIBRATIONWRAPPERSERVICE_QNAME = new QName("http://irwx503.ecpvw.credit.faf.com/", "EcpFinProductCalibrationWrapperService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://af.test.17ebank.com:9167/csmWeb/ws/EcpFinProductCalibrationWrapper?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ECPFINPRODUCTCALIBRATIONWRAPPERSERVICE_WSDL_LOCATION = url;
        ECPFINPRODUCTCALIBRATIONWRAPPERSERVICE_EXCEPTION = e;
    }

    public EcpFinProductCalibrationWrapperService() {
        super(__getWsdlLocation(), ECPFINPRODUCTCALIBRATIONWRAPPERSERVICE_QNAME);
    }

    public EcpFinProductCalibrationWrapperService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ECPFINPRODUCTCALIBRATIONWRAPPERSERVICE_QNAME, features);
    }

    public EcpFinProductCalibrationWrapperService(URL wsdlLocation) {
        super(wsdlLocation, ECPFINPRODUCTCALIBRATIONWRAPPERSERVICE_QNAME);
    }

    public EcpFinProductCalibrationWrapperService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ECPFINPRODUCTCALIBRATIONWRAPPERSERVICE_QNAME, features);
    }

    public EcpFinProductCalibrationWrapperService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EcpFinProductCalibrationWrapperService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EcpFinProductCalibrationWrapper
     */
    @WebEndpoint(name = "EcpFinProductCalibrationWrapperPort")
    public EcpFinProductCalibrationWrapper getEcpFinProductCalibrationWrapperPort() {
        return super.getPort(new QName("http://irwx503.ecpvw.credit.faf.com/", "EcpFinProductCalibrationWrapperPort"), EcpFinProductCalibrationWrapper.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EcpFinProductCalibrationWrapper
     */
    @WebEndpoint(name = "EcpFinProductCalibrationWrapperPort")
    public EcpFinProductCalibrationWrapper getEcpFinProductCalibrationWrapperPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://irwx503.ecpvw.credit.faf.com/", "EcpFinProductCalibrationWrapperPort"), EcpFinProductCalibrationWrapper.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ECPFINPRODUCTCALIBRATIONWRAPPERSERVICE_EXCEPTION!= null) {
            throw ECPFINPRODUCTCALIBRATIONWRAPPERSERVICE_EXCEPTION;
        }
        return ECPFINPRODUCTCALIBRATIONWRAPPERSERVICE_WSDL_LOCATION;
    }

}
