
package com.vw.rent.ws.ecpFinProductCalibrationWrapper;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EcpFinProductCalibrationWrapper", targetNamespace = "http://irwx503.ecpvw.credit.faf.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EcpFinProductCalibrationWrapper {


    /**
     * 
     * @param requestDTO
     * @return
     *     returns com.vw.rent.ws.ecpFinProductCalibrationWrapper.EcpFinProductCalibrationResponseDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLoanProvidePlanner", targetNamespace = "http://irwx503.ecpvw.credit.faf.com/", className = "com.vw.rent.ws.ecpFinProductCalibrationWrapper.GetLoanProvidePlanner")
    @ResponseWrapper(localName = "getLoanProvidePlannerResponse", targetNamespace = "http://irwx503.ecpvw.credit.faf.com/", className = "com.vw.rent.ws.ecpFinProductCalibrationWrapper.GetLoanProvidePlannerResponse")
    public EcpFinProductCalibrationResponseDTO getLoanProvidePlanner(
        @WebParam(name = "requestDTO", targetNamespace = "")
        EcpFinProductCalibrationRequestDTO requestDTO);

}
