server:
  port: 9091


spring:
  datasource:
        url: jdbc:mysql://47.94.15.141:3306/faw_vw?characterEncoding=UTF-8&useSSL=false
        username: faw_vw
        password: fawvw@scfl
        druid:
          initial-size: 0
          max-active: 10
          min-idle: 0
          max-wait-thread-count: 10
          max-wait: 60000
          time-between-eviction-runs-millis: 60000
          filter:
            log4j2:
              data-source-log-enabled: true

  redis:
        database: 0
        host: 127.0.0.1
        port: 6379
        timeout: 3000 # 连接超时时间 单位 ms（毫秒）
        jedis:
          pool:
            max-idle: 500
            min-idle: 50
            max-active: 2000
            max-wait: 1000



