
package com.vw.rent.ws.ecpDictYsxWrapper;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EcpDictYsxWrapper", targetNamespace = "http://irwx508.ecpvw.credit.faf.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EcpDictYsxWrapper {


    /**
     * 
     * @param requestDTO
     * @return
     *     returns com.vw.rent.ws.EcpDictYsxWrapper.EcpDictYsxResponseDTO
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selDictYsxByObject", targetNamespace = "http://irwx508.ecpvw.credit.faf.com/", className = "com.vw.rent.ws.EcpDictYsxWrapper.SelDictYsxByObject")
    @ResponseWrapper(localName = "selDictYsxByObjectResponse", targetNamespace = "http://irwx508.ecpvw.credit.faf.com/", className = "com.vw.rent.ws.EcpDictYsxWrapper.SelDictYsxByObjectResponse")
    public EcpDictYsxResponseDTO selDictYsxByObject(
        @WebParam(name = "requestDTO", targetNamespace = "")
        EcpDictYsxRequestDTO requestDTO)
        throws Exception_Exception
    ;

}
