
package com.vw.rent.ws.ecpDictYsxWrapper;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EcpDictYsxWrapperService", targetNamespace = "http://irwx508.ecpvw.credit.faf.com/", wsdlLocation = "http://af.test.17ebank.com:9167/csmWeb/ws/EcpDictYsxWrapper?wsdl")
public class EcpDictYsxWrapperService
    extends Service
{

    private final static URL ECPDICTYSXWRAPPERSERVICE_WSDL_LOCATION;
    private final static WebServiceException ECPDICTYSXWRAPPERSERVICE_EXCEPTION;
    private final static QName ECPDICTYSXWRAPPERSERVICE_QNAME = new QName("http://irwx508.ecpvw.credit.faf.com/", "EcpDictYsxWrapperService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://af.test.17ebank.com:9167/csmWeb/ws/EcpDictYsxWrapper?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ECPDICTYSXWRAPPERSERVICE_WSDL_LOCATION = url;
        ECPDICTYSXWRAPPERSERVICE_EXCEPTION = e;
    }

    public EcpDictYsxWrapperService() {
        super(__getWsdlLocation(), ECPDICTYSXWRAPPERSERVICE_QNAME);
    }

    public EcpDictYsxWrapperService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ECPDICTYSXWRAPPERSERVICE_QNAME, features);
    }

    public EcpDictYsxWrapperService(URL wsdlLocation) {
        super(wsdlLocation, ECPDICTYSXWRAPPERSERVICE_QNAME);
    }

    public EcpDictYsxWrapperService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ECPDICTYSXWRAPPERSERVICE_QNAME, features);
    }

    public EcpDictYsxWrapperService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EcpDictYsxWrapperService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EcpDictYsxWrapper
     */
    @WebEndpoint(name = "EcpDictYsxWrapperPort")
    public EcpDictYsxWrapper getEcpDictYsxWrapperPort() {
        return super.getPort(new QName("http://irwx508.ecpvw.credit.faf.com/", "EcpDictYsxWrapperPort"), EcpDictYsxWrapper.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EcpDictYsxWrapper
     */
    @WebEndpoint(name = "EcpDictYsxWrapperPort")
    public EcpDictYsxWrapper getEcpDictYsxWrapperPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://irwx508.ecpvw.credit.faf.com/", "EcpDictYsxWrapperPort"), EcpDictYsxWrapper.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ECPDICTYSXWRAPPERSERVICE_EXCEPTION!= null) {
            throw ECPDICTYSXWRAPPERSERVICE_EXCEPTION;
        }
        return ECPDICTYSXWRAPPERSERVICE_WSDL_LOCATION;
    }

}
