
package com.vw.rent.ws.ecpDictYsxWrapper;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "Exception", targetNamespace = "http://irwx508.ecpvw.credit.faf.com/")
public class Exception_Exception
    extends java.lang.Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private com.vw.rent.ws.ecpDictYsxWrapper.Exception faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public Exception_Exception(String message, com.vw.rent.ws.ecpDictYsxWrapper.Exception faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public Exception_Exception(String message, com.vw.rent.ws.ecpDictYsxWrapper.Exception faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.vw.rent.ws.EcpDictYsxWrapper.Exception
     */
    public com.vw.rent.ws.ecpDictYsxWrapper.Exception getFaultInfo() {
        return faultInfo;
    }

}
