package com.vw.rent.entity;

public class Dictionary {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_dictionary.id
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_dictionary.text
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private String text;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_dictionary.value
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private Integer value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_dictionary.typeid
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private Integer typeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_dictionary.order
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private Integer order;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_dictionary.number
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private Integer number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_dictionary.fid
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private Integer fid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_dictionary.astext
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private String astext;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_dictionary.id
     *
     * @return the value of vw_dictionary.id
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_dictionary.id
     *
     * @param id the value for vw_dictionary.id
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_dictionary.text
     *
     * @return the value of vw_dictionary.text
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_dictionary.text
     *
     * @param text the value for vw_dictionary.text
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setText(String text) {
        this.text = text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_dictionary.value
     *
     * @return the value of vw_dictionary.value
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public Integer getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_dictionary.value
     *
     * @param value the value for vw_dictionary.value
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setValue(Integer value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_dictionary.typeid
     *
     * @return the value of vw_dictionary.typeid
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public Integer getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_dictionary.typeid
     *
     * @param typeid the value for vw_dictionary.typeid
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setTypeid(Integer typeid) {
        this.typeid = typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_dictionary.order
     *
     * @return the value of vw_dictionary.order
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public Integer getOrder() {
        return order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_dictionary.order
     *
     * @param order the value for vw_dictionary.order
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setOrder(Integer order) {
        this.order = order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_dictionary.number
     *
     * @return the value of vw_dictionary.number
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_dictionary.number
     *
     * @param number the value for vw_dictionary.number
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_dictionary.fid
     *
     * @return the value of vw_dictionary.fid
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public Integer getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_dictionary.fid
     *
     * @param fid the value for vw_dictionary.fid
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setFid(Integer fid) {
        this.fid = fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_dictionary.astext
     *
     * @return the value of vw_dictionary.astext
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public String getAstext() {
        return astext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_dictionary.astext
     *
     * @param astext the value for vw_dictionary.astext
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setAstext(String astext) {
        this.astext = astext;
    }
}