package com.vw.rent.entity;

public class DictionaryType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_dictionary_type.id
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_dictionary_type.typename
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private String typename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_dictionary_type.typeexplain
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private String typeexplain;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_dictionary_type.id
     *
     * @return the value of vw_dictionary_type.id
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_dictionary_type.id
     *
     * @param id the value for vw_dictionary_type.id
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_dictionary_type.typename
     *
     * @return the value of vw_dictionary_type.typename
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public String getTypename() {
        return typename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_dictionary_type.typename
     *
     * @param typename the value for vw_dictionary_type.typename
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setTypename(String typename) {
        this.typename = typename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_dictionary_type.typeexplain
     *
     * @return the value of vw_dictionary_type.typeexplain
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public String getTypeexplain() {
        return typeexplain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_dictionary_type.typeexplain
     *
     * @param typeexplain the value for vw_dictionary_type.typeexplain
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setTypeexplain(String typeexplain) {
        this.typeexplain = typeexplain;
    }
}