package com.vw.rent.entity;

public class OrderStatusChange {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_status_change.id
     *
     * @mbg.generated Fri Dec 27 10:37:17 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_status_change.order_no
     *
     * @mbg.generated Fri Dec 27 10:37:17 CST 2019
     */
    private String orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_status_change.status
     *
     * @mbg.generated Fri Dec 27 10:37:17 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_status_change.create_time
     *
     * @mbg.generated Fri Dec 27 10:37:17 CST 2019
     */
    private Integer createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_status_change.spres_year
     *
     * @mbg.generated Fri Dec 27 10:37:17 CST 2019
     */
    private String spresYear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_status_change.spres_week
     *
     * @mbg.generated Fri Dec 27 10:37:17 CST 2019
     */
    private String spresWeek;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_status_change.status_msg
     *
     * @mbg.generated Fri Dec 27 10:37:17 CST 2019
     */
    private String statusMsg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_status_change.id
     *
     * @return the value of vw_order_status_change.id
     *
     * @mbg.generated Fri Dec 27 10:37:17 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_status_change.id
     *
     * @param id the value for vw_order_status_change.id
     *
     * @mbg.generated Fri Dec 27 10:37:17 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_status_change.order_no
     *
     * @return the value of vw_order_status_change.order_no
     *
     * @mbg.generated Fri Dec 27 10:37:17 CST 2019
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_status_change.order_no
     *
     * @param orderNo the value for vw_order_status_change.order_no
     *
     * @mbg.generated Fri Dec 27 10:37:17 CST 2019
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_status_change.status
     *
     * @return the value of vw_order_status_change.status
     *
     * @mbg.generated Fri Dec 27 10:37:17 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_status_change.status
     *
     * @param status the value for vw_order_status_change.status
     *
     * @mbg.generated Fri Dec 27 10:37:17 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_status_change.create_time
     *
     * @return the value of vw_order_status_change.create_time
     *
     * @mbg.generated Fri Dec 27 10:37:17 CST 2019
     */
    public Integer getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_status_change.create_time
     *
     * @param createTime the value for vw_order_status_change.create_time
     *
     * @mbg.generated Fri Dec 27 10:37:17 CST 2019
     */
    public void setCreateTime(Integer createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_status_change.spres_year
     *
     * @return the value of vw_order_status_change.spres_year
     *
     * @mbg.generated Fri Dec 27 10:37:17 CST 2019
     */
    public String getSpresYear() {
        return spresYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_status_change.spres_year
     *
     * @param spresYear the value for vw_order_status_change.spres_year
     *
     * @mbg.generated Fri Dec 27 10:37:17 CST 2019
     */
    public void setSpresYear(String spresYear) {
        this.spresYear = spresYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_status_change.spres_week
     *
     * @return the value of vw_order_status_change.spres_week
     *
     * @mbg.generated Fri Dec 27 10:37:17 CST 2019
     */
    public String getSpresWeek() {
        return spresWeek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_status_change.spres_week
     *
     * @param spresWeek the value for vw_order_status_change.spres_week
     *
     * @mbg.generated Fri Dec 27 10:37:17 CST 2019
     */
    public void setSpresWeek(String spresWeek) {
        this.spresWeek = spresWeek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_status_change.status_msg
     *
     * @return the value of vw_order_status_change.status_msg
     *
     * @mbg.generated Fri Dec 27 10:37:17 CST 2019
     */
    public String getStatusMsg() {
        return statusMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_status_change.status_msg
     *
     * @param statusMsg the value for vw_order_status_change.status_msg
     *
     * @mbg.generated Fri Dec 27 10:37:17 CST 2019
     */
    public void setStatusMsg(String statusMsg) {
        this.statusMsg = statusMsg;
    }
}