package com.vw.rent.entity;

public class OrderRentNew {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_rent_new.new_id
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private Integer newId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_rent_new.order_no
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private String orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_rent_new.contactName
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private String contactname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_rent_new.gender
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_rent_new.contactPhoneNumber
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private String contactphonenumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_rent_new.email
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_rent_new.birthday
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private String birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_rent_new.idDocumentType
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private String iddocumenttype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_rent_new.idNumber
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private String idnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_rent_new.idEffectiveDateFrom
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private String ideffectivedatefrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_rent_new.idEffectiveDateTo
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private String ideffectivedateto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_rent_new.idProvinceId
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private String idprovinceid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_rent_new.idCityId
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private String idcityid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_rent_new.idDistrict
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private String iddistrict;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_rent_new.idAddress
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private String idaddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_rent_new.idDeliveryCountry
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private String iddeliverycountry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_rent_new.maritalStatus
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private String maritalstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_rent_new.relationsName
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private String relationsname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_rent_new.relationsPhoneNumber
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private String relationsphonenumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_rent_new.relationsIdDocumentType
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private String relationsiddocumenttype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_rent_new.relationsIdNumber
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private String relationsidnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_rent_new.relationsIdEffectiveDateFrom
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private String relationsideffectivedatefrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_rent_new.relationsIdEffectiveDateTo
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private String relationsideffectivedateto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_rent_new.relationsIdDeliveryCountry
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private String relationsiddeliverycountry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_rent_new.housePropertyType
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private String housepropertytype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_rent_new.provinceId
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private String provinceid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_rent_new.cityId
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private String cityid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_rent_new.district
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private String district;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_rent_new.contactAddress
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private String contactaddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_rent_new.residenceYear
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private String residenceyear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_rent_new.industryCode
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private String industrycode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_rent_new.employerName
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private String employername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_rent_new.investorType
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private String investortype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_rent_new.occupation
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private String occupation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_rent_new.yearOfEmployment
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private String yearofemployment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_rent_new.position
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private String position;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_rent_new.professionalTitle
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private String professionaltitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_rent_new.companyProvinceId
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private String companyprovinceid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_rent_new.companyCityId
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private String companycityid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_rent_new.companyArea
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private String companyarea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_rent_new.companyAddress
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private String companyaddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_rent_new.mailingAddressType
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private String mailingaddresstype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_rent_new.monthlyIncome
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private String monthlyincome;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_rent_new.monthlyExpense
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private String monthlyexpense;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_rent_new.education
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private String education;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_rent_new.degree
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private String degree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_rent_new.dealerId
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private String dealerid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_rent_new.applicationNo
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private String applicationno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_rent_new.productId
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private String productid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_rent_new.depositAmount
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private String depositamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_rent_new.modelCode
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private String modelcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_rent_new.vehiclePrice
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private String vehicleprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_rent_new.tenor
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private String tenor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_rent_new.totalAmount
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private String totalamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_rent_new.monthlyInstallment
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private String monthlyinstallment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_rent_new.interestRate
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private String interestrate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_rent_new.downPaymentAmount
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private String downpaymentamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_rent_new.balloonAmount
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private String balloonamount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_rent_new.new_id
     *
     * @return the value of vw_order_rent_new.new_id
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public Integer getNewId() {
        return newId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_rent_new.new_id
     *
     * @param newId the value for vw_order_rent_new.new_id
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setNewId(Integer newId) {
        this.newId = newId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_rent_new.order_no
     *
     * @return the value of vw_order_rent_new.order_no
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_rent_new.order_no
     *
     * @param orderNo the value for vw_order_rent_new.order_no
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_rent_new.contactName
     *
     * @return the value of vw_order_rent_new.contactName
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public String getContactname() {
        return contactname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_rent_new.contactName
     *
     * @param contactname the value for vw_order_rent_new.contactName
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setContactname(String contactname) {
        this.contactname = contactname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_rent_new.gender
     *
     * @return the value of vw_order_rent_new.gender
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_rent_new.gender
     *
     * @param gender the value for vw_order_rent_new.gender
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_rent_new.contactPhoneNumber
     *
     * @return the value of vw_order_rent_new.contactPhoneNumber
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public String getContactphonenumber() {
        return contactphonenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_rent_new.contactPhoneNumber
     *
     * @param contactphonenumber the value for vw_order_rent_new.contactPhoneNumber
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setContactphonenumber(String contactphonenumber) {
        this.contactphonenumber = contactphonenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_rent_new.email
     *
     * @return the value of vw_order_rent_new.email
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_rent_new.email
     *
     * @param email the value for vw_order_rent_new.email
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_rent_new.birthday
     *
     * @return the value of vw_order_rent_new.birthday
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_rent_new.birthday
     *
     * @param birthday the value for vw_order_rent_new.birthday
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_rent_new.idDocumentType
     *
     * @return the value of vw_order_rent_new.idDocumentType
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public String getIddocumenttype() {
        return iddocumenttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_rent_new.idDocumentType
     *
     * @param iddocumenttype the value for vw_order_rent_new.idDocumentType
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setIddocumenttype(String iddocumenttype) {
        this.iddocumenttype = iddocumenttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_rent_new.idNumber
     *
     * @return the value of vw_order_rent_new.idNumber
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public String getIdnumber() {
        return idnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_rent_new.idNumber
     *
     * @param idnumber the value for vw_order_rent_new.idNumber
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setIdnumber(String idnumber) {
        this.idnumber = idnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_rent_new.idEffectiveDateFrom
     *
     * @return the value of vw_order_rent_new.idEffectiveDateFrom
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public String getIdeffectivedatefrom() {
        return ideffectivedatefrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_rent_new.idEffectiveDateFrom
     *
     * @param ideffectivedatefrom the value for vw_order_rent_new.idEffectiveDateFrom
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setIdeffectivedatefrom(String ideffectivedatefrom) {
        this.ideffectivedatefrom = ideffectivedatefrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_rent_new.idEffectiveDateTo
     *
     * @return the value of vw_order_rent_new.idEffectiveDateTo
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public String getIdeffectivedateto() {
        return ideffectivedateto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_rent_new.idEffectiveDateTo
     *
     * @param ideffectivedateto the value for vw_order_rent_new.idEffectiveDateTo
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setIdeffectivedateto(String ideffectivedateto) {
        this.ideffectivedateto = ideffectivedateto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_rent_new.idProvinceId
     *
     * @return the value of vw_order_rent_new.idProvinceId
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public String getIdprovinceid() {
        return idprovinceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_rent_new.idProvinceId
     *
     * @param idprovinceid the value for vw_order_rent_new.idProvinceId
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setIdprovinceid(String idprovinceid) {
        this.idprovinceid = idprovinceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_rent_new.idCityId
     *
     * @return the value of vw_order_rent_new.idCityId
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public String getIdcityid() {
        return idcityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_rent_new.idCityId
     *
     * @param idcityid the value for vw_order_rent_new.idCityId
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setIdcityid(String idcityid) {
        this.idcityid = idcityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_rent_new.idDistrict
     *
     * @return the value of vw_order_rent_new.idDistrict
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public String getIddistrict() {
        return iddistrict;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_rent_new.idDistrict
     *
     * @param iddistrict the value for vw_order_rent_new.idDistrict
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setIddistrict(String iddistrict) {
        this.iddistrict = iddistrict;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_rent_new.idAddress
     *
     * @return the value of vw_order_rent_new.idAddress
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public String getIdaddress() {
        return idaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_rent_new.idAddress
     *
     * @param idaddress the value for vw_order_rent_new.idAddress
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setIdaddress(String idaddress) {
        this.idaddress = idaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_rent_new.idDeliveryCountry
     *
     * @return the value of vw_order_rent_new.idDeliveryCountry
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public String getIddeliverycountry() {
        return iddeliverycountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_rent_new.idDeliveryCountry
     *
     * @param iddeliverycountry the value for vw_order_rent_new.idDeliveryCountry
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setIddeliverycountry(String iddeliverycountry) {
        this.iddeliverycountry = iddeliverycountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_rent_new.maritalStatus
     *
     * @return the value of vw_order_rent_new.maritalStatus
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public String getMaritalstatus() {
        return maritalstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_rent_new.maritalStatus
     *
     * @param maritalstatus the value for vw_order_rent_new.maritalStatus
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setMaritalstatus(String maritalstatus) {
        this.maritalstatus = maritalstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_rent_new.relationsName
     *
     * @return the value of vw_order_rent_new.relationsName
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public String getRelationsname() {
        return relationsname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_rent_new.relationsName
     *
     * @param relationsname the value for vw_order_rent_new.relationsName
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setRelationsname(String relationsname) {
        this.relationsname = relationsname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_rent_new.relationsPhoneNumber
     *
     * @return the value of vw_order_rent_new.relationsPhoneNumber
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public String getRelationsphonenumber() {
        return relationsphonenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_rent_new.relationsPhoneNumber
     *
     * @param relationsphonenumber the value for vw_order_rent_new.relationsPhoneNumber
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setRelationsphonenumber(String relationsphonenumber) {
        this.relationsphonenumber = relationsphonenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_rent_new.relationsIdDocumentType
     *
     * @return the value of vw_order_rent_new.relationsIdDocumentType
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public String getRelationsiddocumenttype() {
        return relationsiddocumenttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_rent_new.relationsIdDocumentType
     *
     * @param relationsiddocumenttype the value for vw_order_rent_new.relationsIdDocumentType
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setRelationsiddocumenttype(String relationsiddocumenttype) {
        this.relationsiddocumenttype = relationsiddocumenttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_rent_new.relationsIdNumber
     *
     * @return the value of vw_order_rent_new.relationsIdNumber
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public String getRelationsidnumber() {
        return relationsidnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_rent_new.relationsIdNumber
     *
     * @param relationsidnumber the value for vw_order_rent_new.relationsIdNumber
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setRelationsidnumber(String relationsidnumber) {
        this.relationsidnumber = relationsidnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_rent_new.relationsIdEffectiveDateFrom
     *
     * @return the value of vw_order_rent_new.relationsIdEffectiveDateFrom
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public String getRelationsideffectivedatefrom() {
        return relationsideffectivedatefrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_rent_new.relationsIdEffectiveDateFrom
     *
     * @param relationsideffectivedatefrom the value for vw_order_rent_new.relationsIdEffectiveDateFrom
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setRelationsideffectivedatefrom(String relationsideffectivedatefrom) {
        this.relationsideffectivedatefrom = relationsideffectivedatefrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_rent_new.relationsIdEffectiveDateTo
     *
     * @return the value of vw_order_rent_new.relationsIdEffectiveDateTo
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public String getRelationsideffectivedateto() {
        return relationsideffectivedateto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_rent_new.relationsIdEffectiveDateTo
     *
     * @param relationsideffectivedateto the value for vw_order_rent_new.relationsIdEffectiveDateTo
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setRelationsideffectivedateto(String relationsideffectivedateto) {
        this.relationsideffectivedateto = relationsideffectivedateto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_rent_new.relationsIdDeliveryCountry
     *
     * @return the value of vw_order_rent_new.relationsIdDeliveryCountry
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public String getRelationsiddeliverycountry() {
        return relationsiddeliverycountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_rent_new.relationsIdDeliveryCountry
     *
     * @param relationsiddeliverycountry the value for vw_order_rent_new.relationsIdDeliveryCountry
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setRelationsiddeliverycountry(String relationsiddeliverycountry) {
        this.relationsiddeliverycountry = relationsiddeliverycountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_rent_new.housePropertyType
     *
     * @return the value of vw_order_rent_new.housePropertyType
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public String getHousepropertytype() {
        return housepropertytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_rent_new.housePropertyType
     *
     * @param housepropertytype the value for vw_order_rent_new.housePropertyType
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setHousepropertytype(String housepropertytype) {
        this.housepropertytype = housepropertytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_rent_new.provinceId
     *
     * @return the value of vw_order_rent_new.provinceId
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public String getProvinceid() {
        return provinceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_rent_new.provinceId
     *
     * @param provinceid the value for vw_order_rent_new.provinceId
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setProvinceid(String provinceid) {
        this.provinceid = provinceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_rent_new.cityId
     *
     * @return the value of vw_order_rent_new.cityId
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public String getCityid() {
        return cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_rent_new.cityId
     *
     * @param cityid the value for vw_order_rent_new.cityId
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setCityid(String cityid) {
        this.cityid = cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_rent_new.district
     *
     * @return the value of vw_order_rent_new.district
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public String getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_rent_new.district
     *
     * @param district the value for vw_order_rent_new.district
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setDistrict(String district) {
        this.district = district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_rent_new.contactAddress
     *
     * @return the value of vw_order_rent_new.contactAddress
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public String getContactaddress() {
        return contactaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_rent_new.contactAddress
     *
     * @param contactaddress the value for vw_order_rent_new.contactAddress
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setContactaddress(String contactaddress) {
        this.contactaddress = contactaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_rent_new.residenceYear
     *
     * @return the value of vw_order_rent_new.residenceYear
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public String getResidenceyear() {
        return residenceyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_rent_new.residenceYear
     *
     * @param residenceyear the value for vw_order_rent_new.residenceYear
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setResidenceyear(String residenceyear) {
        this.residenceyear = residenceyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_rent_new.industryCode
     *
     * @return the value of vw_order_rent_new.industryCode
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public String getIndustrycode() {
        return industrycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_rent_new.industryCode
     *
     * @param industrycode the value for vw_order_rent_new.industryCode
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setIndustrycode(String industrycode) {
        this.industrycode = industrycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_rent_new.employerName
     *
     * @return the value of vw_order_rent_new.employerName
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public String getEmployername() {
        return employername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_rent_new.employerName
     *
     * @param employername the value for vw_order_rent_new.employerName
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setEmployername(String employername) {
        this.employername = employername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_rent_new.investorType
     *
     * @return the value of vw_order_rent_new.investorType
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public String getInvestortype() {
        return investortype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_rent_new.investorType
     *
     * @param investortype the value for vw_order_rent_new.investorType
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setInvestortype(String investortype) {
        this.investortype = investortype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_rent_new.occupation
     *
     * @return the value of vw_order_rent_new.occupation
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public String getOccupation() {
        return occupation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_rent_new.occupation
     *
     * @param occupation the value for vw_order_rent_new.occupation
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setOccupation(String occupation) {
        this.occupation = occupation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_rent_new.yearOfEmployment
     *
     * @return the value of vw_order_rent_new.yearOfEmployment
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public String getYearofemployment() {
        return yearofemployment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_rent_new.yearOfEmployment
     *
     * @param yearofemployment the value for vw_order_rent_new.yearOfEmployment
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setYearofemployment(String yearofemployment) {
        this.yearofemployment = yearofemployment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_rent_new.position
     *
     * @return the value of vw_order_rent_new.position
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_rent_new.position
     *
     * @param position the value for vw_order_rent_new.position
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setPosition(String position) {
        this.position = position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_rent_new.professionalTitle
     *
     * @return the value of vw_order_rent_new.professionalTitle
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public String getProfessionaltitle() {
        return professionaltitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_rent_new.professionalTitle
     *
     * @param professionaltitle the value for vw_order_rent_new.professionalTitle
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setProfessionaltitle(String professionaltitle) {
        this.professionaltitle = professionaltitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_rent_new.companyProvinceId
     *
     * @return the value of vw_order_rent_new.companyProvinceId
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public String getCompanyprovinceid() {
        return companyprovinceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_rent_new.companyProvinceId
     *
     * @param companyprovinceid the value for vw_order_rent_new.companyProvinceId
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setCompanyprovinceid(String companyprovinceid) {
        this.companyprovinceid = companyprovinceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_rent_new.companyCityId
     *
     * @return the value of vw_order_rent_new.companyCityId
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public String getCompanycityid() {
        return companycityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_rent_new.companyCityId
     *
     * @param companycityid the value for vw_order_rent_new.companyCityId
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setCompanycityid(String companycityid) {
        this.companycityid = companycityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_rent_new.companyArea
     *
     * @return the value of vw_order_rent_new.companyArea
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public String getCompanyarea() {
        return companyarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_rent_new.companyArea
     *
     * @param companyarea the value for vw_order_rent_new.companyArea
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setCompanyarea(String companyarea) {
        this.companyarea = companyarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_rent_new.companyAddress
     *
     * @return the value of vw_order_rent_new.companyAddress
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public String getCompanyaddress() {
        return companyaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_rent_new.companyAddress
     *
     * @param companyaddress the value for vw_order_rent_new.companyAddress
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setCompanyaddress(String companyaddress) {
        this.companyaddress = companyaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_rent_new.mailingAddressType
     *
     * @return the value of vw_order_rent_new.mailingAddressType
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public String getMailingaddresstype() {
        return mailingaddresstype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_rent_new.mailingAddressType
     *
     * @param mailingaddresstype the value for vw_order_rent_new.mailingAddressType
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setMailingaddresstype(String mailingaddresstype) {
        this.mailingaddresstype = mailingaddresstype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_rent_new.monthlyIncome
     *
     * @return the value of vw_order_rent_new.monthlyIncome
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public String getMonthlyincome() {
        return monthlyincome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_rent_new.monthlyIncome
     *
     * @param monthlyincome the value for vw_order_rent_new.monthlyIncome
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setMonthlyincome(String monthlyincome) {
        this.monthlyincome = monthlyincome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_rent_new.monthlyExpense
     *
     * @return the value of vw_order_rent_new.monthlyExpense
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public String getMonthlyexpense() {
        return monthlyexpense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_rent_new.monthlyExpense
     *
     * @param monthlyexpense the value for vw_order_rent_new.monthlyExpense
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setMonthlyexpense(String monthlyexpense) {
        this.monthlyexpense = monthlyexpense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_rent_new.education
     *
     * @return the value of vw_order_rent_new.education
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public String getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_rent_new.education
     *
     * @param education the value for vw_order_rent_new.education
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setEducation(String education) {
        this.education = education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_rent_new.degree
     *
     * @return the value of vw_order_rent_new.degree
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public String getDegree() {
        return degree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_rent_new.degree
     *
     * @param degree the value for vw_order_rent_new.degree
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setDegree(String degree) {
        this.degree = degree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_rent_new.dealerId
     *
     * @return the value of vw_order_rent_new.dealerId
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public String getDealerid() {
        return dealerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_rent_new.dealerId
     *
     * @param dealerid the value for vw_order_rent_new.dealerId
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setDealerid(String dealerid) {
        this.dealerid = dealerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_rent_new.applicationNo
     *
     * @return the value of vw_order_rent_new.applicationNo
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public String getApplicationno() {
        return applicationno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_rent_new.applicationNo
     *
     * @param applicationno the value for vw_order_rent_new.applicationNo
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setApplicationno(String applicationno) {
        this.applicationno = applicationno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_rent_new.productId
     *
     * @return the value of vw_order_rent_new.productId
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public String getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_rent_new.productId
     *
     * @param productid the value for vw_order_rent_new.productId
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setProductid(String productid) {
        this.productid = productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_rent_new.depositAmount
     *
     * @return the value of vw_order_rent_new.depositAmount
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public String getDepositamount() {
        return depositamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_rent_new.depositAmount
     *
     * @param depositamount the value for vw_order_rent_new.depositAmount
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setDepositamount(String depositamount) {
        this.depositamount = depositamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_rent_new.modelCode
     *
     * @return the value of vw_order_rent_new.modelCode
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public String getModelcode() {
        return modelcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_rent_new.modelCode
     *
     * @param modelcode the value for vw_order_rent_new.modelCode
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setModelcode(String modelcode) {
        this.modelcode = modelcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_rent_new.vehiclePrice
     *
     * @return the value of vw_order_rent_new.vehiclePrice
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public String getVehicleprice() {
        return vehicleprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_rent_new.vehiclePrice
     *
     * @param vehicleprice the value for vw_order_rent_new.vehiclePrice
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setVehicleprice(String vehicleprice) {
        this.vehicleprice = vehicleprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_rent_new.tenor
     *
     * @return the value of vw_order_rent_new.tenor
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public String getTenor() {
        return tenor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_rent_new.tenor
     *
     * @param tenor the value for vw_order_rent_new.tenor
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setTenor(String tenor) {
        this.tenor = tenor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_rent_new.totalAmount
     *
     * @return the value of vw_order_rent_new.totalAmount
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public String getTotalamount() {
        return totalamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_rent_new.totalAmount
     *
     * @param totalamount the value for vw_order_rent_new.totalAmount
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setTotalamount(String totalamount) {
        this.totalamount = totalamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_rent_new.monthlyInstallment
     *
     * @return the value of vw_order_rent_new.monthlyInstallment
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public String getMonthlyinstallment() {
        return monthlyinstallment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_rent_new.monthlyInstallment
     *
     * @param monthlyinstallment the value for vw_order_rent_new.monthlyInstallment
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setMonthlyinstallment(String monthlyinstallment) {
        this.monthlyinstallment = monthlyinstallment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_rent_new.interestRate
     *
     * @return the value of vw_order_rent_new.interestRate
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public String getInterestrate() {
        return interestrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_rent_new.interestRate
     *
     * @param interestrate the value for vw_order_rent_new.interestRate
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setInterestrate(String interestrate) {
        this.interestrate = interestrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_rent_new.downPaymentAmount
     *
     * @return the value of vw_order_rent_new.downPaymentAmount
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public String getDownpaymentamount() {
        return downpaymentamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_rent_new.downPaymentAmount
     *
     * @param downpaymentamount the value for vw_order_rent_new.downPaymentAmount
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setDownpaymentamount(String downpaymentamount) {
        this.downpaymentamount = downpaymentamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_rent_new.balloonAmount
     *
     * @return the value of vw_order_rent_new.balloonAmount
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public String getBalloonamount() {
        return balloonamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_rent_new.balloonAmount
     *
     * @param balloonamount the value for vw_order_rent_new.balloonAmount
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setBalloonamount(String balloonamount) {
        this.balloonamount = balloonamount;
    }
}