package com.vw.rent.entity;

import java.util.Date;

public class OrderRent {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_rent.order_rent_id
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private Integer orderRentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_rent.order_no
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private String orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_rent.applybasic_id
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private String applybasicId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_rent.cid
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_rent.new_vehicle_id
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private Integer newVehicleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_rent.vehicle
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private String vehicle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_rent.material_code
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private String materialCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_rent.down_payment
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private String downPayment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_rent.monthly_supply
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private String monthlySupply;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_rent.company
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private String company;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_rent.company_type
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private Integer companyType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_rent.rent_program
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private Integer rentProgram;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_rent.lease_period
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private String leasePeriod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_rent.tail
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private String tail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_rent.q_mobile
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private String qMobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_rent.contract_url
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private String contractUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_rent.address_p
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private String addressP;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_rent.address_c
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private String addressC;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_rent.address_d
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private String addressD;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_rent.api_addorder
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private Integer apiAddorder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_rent.ascription
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private Byte ascription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_rent.create_at
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private Date createAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_rent.update_at
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private Date updateAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_rent.img_upload1
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private String imgUpload1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_rent.img_upload2
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private String imgUpload2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vw_order_rent.img_upload3
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    private String imgUpload3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_rent.order_rent_id
     *
     * @return the value of vw_order_rent.order_rent_id
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public Integer getOrderRentId() {
        return orderRentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_rent.order_rent_id
     *
     * @param orderRentId the value for vw_order_rent.order_rent_id
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setOrderRentId(Integer orderRentId) {
        this.orderRentId = orderRentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_rent.order_no
     *
     * @return the value of vw_order_rent.order_no
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_rent.order_no
     *
     * @param orderNo the value for vw_order_rent.order_no
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_rent.applybasic_id
     *
     * @return the value of vw_order_rent.applybasic_id
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public String getApplybasicId() {
        return applybasicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_rent.applybasic_id
     *
     * @param applybasicId the value for vw_order_rent.applybasic_id
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setApplybasicId(String applybasicId) {
        this.applybasicId = applybasicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_rent.cid
     *
     * @return the value of vw_order_rent.cid
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_rent.cid
     *
     * @param cid the value for vw_order_rent.cid
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_rent.new_vehicle_id
     *
     * @return the value of vw_order_rent.new_vehicle_id
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public Integer getNewVehicleId() {
        return newVehicleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_rent.new_vehicle_id
     *
     * @param newVehicleId the value for vw_order_rent.new_vehicle_id
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setNewVehicleId(Integer newVehicleId) {
        this.newVehicleId = newVehicleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_rent.vehicle
     *
     * @return the value of vw_order_rent.vehicle
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public String getVehicle() {
        return vehicle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_rent.vehicle
     *
     * @param vehicle the value for vw_order_rent.vehicle
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setVehicle(String vehicle) {
        this.vehicle = vehicle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_rent.material_code
     *
     * @return the value of vw_order_rent.material_code
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public String getMaterialCode() {
        return materialCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_rent.material_code
     *
     * @param materialCode the value for vw_order_rent.material_code
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setMaterialCode(String materialCode) {
        this.materialCode = materialCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_rent.down_payment
     *
     * @return the value of vw_order_rent.down_payment
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public String getDownPayment() {
        return downPayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_rent.down_payment
     *
     * @param downPayment the value for vw_order_rent.down_payment
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setDownPayment(String downPayment) {
        this.downPayment = downPayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_rent.monthly_supply
     *
     * @return the value of vw_order_rent.monthly_supply
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public String getMonthlySupply() {
        return monthlySupply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_rent.monthly_supply
     *
     * @param monthlySupply the value for vw_order_rent.monthly_supply
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setMonthlySupply(String monthlySupply) {
        this.monthlySupply = monthlySupply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_rent.company
     *
     * @return the value of vw_order_rent.company
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_rent.company
     *
     * @param company the value for vw_order_rent.company
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setCompany(String company) {
        this.company = company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_rent.company_type
     *
     * @return the value of vw_order_rent.company_type
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public Integer getCompanyType() {
        return companyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_rent.company_type
     *
     * @param companyType the value for vw_order_rent.company_type
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setCompanyType(Integer companyType) {
        this.companyType = companyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_rent.rent_program
     *
     * @return the value of vw_order_rent.rent_program
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public Integer getRentProgram() {
        return rentProgram;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_rent.rent_program
     *
     * @param rentProgram the value for vw_order_rent.rent_program
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setRentProgram(Integer rentProgram) {
        this.rentProgram = rentProgram;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_rent.lease_period
     *
     * @return the value of vw_order_rent.lease_period
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public String getLeasePeriod() {
        return leasePeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_rent.lease_period
     *
     * @param leasePeriod the value for vw_order_rent.lease_period
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setLeasePeriod(String leasePeriod) {
        this.leasePeriod = leasePeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_rent.tail
     *
     * @return the value of vw_order_rent.tail
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public String getTail() {
        return tail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_rent.tail
     *
     * @param tail the value for vw_order_rent.tail
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setTail(String tail) {
        this.tail = tail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_rent.q_mobile
     *
     * @return the value of vw_order_rent.q_mobile
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public String getqMobile() {
        return qMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_rent.q_mobile
     *
     * @param qMobile the value for vw_order_rent.q_mobile
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setqMobile(String qMobile) {
        this.qMobile = qMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_rent.contract_url
     *
     * @return the value of vw_order_rent.contract_url
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public String getContractUrl() {
        return contractUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_rent.contract_url
     *
     * @param contractUrl the value for vw_order_rent.contract_url
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setContractUrl(String contractUrl) {
        this.contractUrl = contractUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_rent.address_p
     *
     * @return the value of vw_order_rent.address_p
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public String getAddressP() {
        return addressP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_rent.address_p
     *
     * @param addressP the value for vw_order_rent.address_p
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setAddressP(String addressP) {
        this.addressP = addressP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_rent.address_c
     *
     * @return the value of vw_order_rent.address_c
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public String getAddressC() {
        return addressC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_rent.address_c
     *
     * @param addressC the value for vw_order_rent.address_c
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setAddressC(String addressC) {
        this.addressC = addressC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_rent.address_d
     *
     * @return the value of vw_order_rent.address_d
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public String getAddressD() {
        return addressD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_rent.address_d
     *
     * @param addressD the value for vw_order_rent.address_d
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setAddressD(String addressD) {
        this.addressD = addressD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_rent.api_addorder
     *
     * @return the value of vw_order_rent.api_addorder
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public Integer getApiAddorder() {
        return apiAddorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_rent.api_addorder
     *
     * @param apiAddorder the value for vw_order_rent.api_addorder
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setApiAddorder(Integer apiAddorder) {
        this.apiAddorder = apiAddorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_rent.ascription
     *
     * @return the value of vw_order_rent.ascription
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public Byte getAscription() {
        return ascription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_rent.ascription
     *
     * @param ascription the value for vw_order_rent.ascription
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setAscription(Byte ascription) {
        this.ascription = ascription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_rent.create_at
     *
     * @return the value of vw_order_rent.create_at
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_rent.create_at
     *
     * @param createAt the value for vw_order_rent.create_at
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_rent.update_at
     *
     * @return the value of vw_order_rent.update_at
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_rent.update_at
     *
     * @param updateAt the value for vw_order_rent.update_at
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_rent.img_upload1
     *
     * @return the value of vw_order_rent.img_upload1
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public String getImgUpload1() {
        return imgUpload1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_rent.img_upload1
     *
     * @param imgUpload1 the value for vw_order_rent.img_upload1
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setImgUpload1(String imgUpload1) {
        this.imgUpload1 = imgUpload1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_rent.img_upload2
     *
     * @return the value of vw_order_rent.img_upload2
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public String getImgUpload2() {
        return imgUpload2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_rent.img_upload2
     *
     * @param imgUpload2 the value for vw_order_rent.img_upload2
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setImgUpload2(String imgUpload2) {
        this.imgUpload2 = imgUpload2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vw_order_rent.img_upload3
     *
     * @return the value of vw_order_rent.img_upload3
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public String getImgUpload3() {
        return imgUpload3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vw_order_rent.img_upload3
     *
     * @param imgUpload3 the value for vw_order_rent.img_upload3
     *
     * @mbg.generated Fri Dec 27 10:19:20 CST 2019
     */
    public void setImgUpload3(String imgUpload3) {
        this.imgUpload3 = imgUpload3;
    }
}